export type SdtStep = { id: string; name?: string; kind: 'click' | 'input' | 'key' | 'wait' | 'url' | 'assert-visible' | 'assert-text' | 'screenshot'; selector?: string; x?: number; y?: number; value?: string; expectedValue?: string; ms?: number; timeoutMs?: number; sensitive?: boolean }
export type SdtTest = { id: string; site: string; suiteId?: string; name: string; steps: SdtStep[]; updatedAt: number }
export type SdtProject = { id:string; site:string; name:string; baseUrl:string; defaultTimeoutMs:number; traceEnabled:boolean }
export type SdtSuite = { id:string; projectId:string; name:string }
export type SdtColor = { label: string; css: string; hex: string | null; rgb: string | null }
export type SdtSelection = { selector: string; colors: SdtColor[]; typography?: { fontFamily: string; fontSize: string; fontWeight: string; lineHeight: string } }
export type SdtApiRequest = { url: string; method: 'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE' | 'HEAD'; headers: { name: string; value: string }[]; body: string; bodyType: 'json' | 'text' }
export type SdtApiResult = { status: number; statusText: string; elapsedMs: number; headers: { name: string; value: string }[]; body: string; bytes: number; error?: string }
export type SdtStepResult = { id: string; name?: string; status: 'running' | 'passed' | 'failed' | 'cancelled'; message?: string; durationMs?: number; screenshot?: string; domSnapshot?: string; currentUrl?: string; console?: string[]; network?: { method:string; host:string; path:string; status?:number; error?:string }[]; locatorCandidates?: string[] }
export type SdtRun = { id: string; site: string; name: string; startedAt: number; durationMs: number; status: 'passed' | 'failed' | 'cancelled'; passed: number; failed: number; cancelled: number; results: SdtStepResult[] }
export type SdtState = { enabled: boolean; open: boolean; tabId: string | null; site: string | null; url: string; mode: 'idle' | 'picking' | 'recording' | 'running'; selection: SdtSelection | null; draft: SdtStep[]; tests: SdtTest[]; projects:SdtProject[]; suites:SdtSuite[]; runs: SdtRun[]; results: SdtStepResult[]; activeRunId: string | null; apiRunning: boolean; apiResult: SdtApiResult | null; message: string }
export type SdtReply = { ok: boolean; error?: string; data?: unknown }
