/* Runs the actual application in an isolated temporary profile. No user profile is opened. */
const { app, BrowserWindow, clipboard, webContents, session } = require('electron')
const fs = require('node:fs')
const os = require('node:os')
const path = require('node:path')
const http = require('node:http')
const assert = require('node:assert/strict')
const taskRoot = fs.mkdtempSync(path.join(os.tmpdir(), 'skipy-sdt-smoke-'))
const appData = path.join(taskRoot, 'appdata')
fs.mkdirSync(appData, { recursive: true })
app.setPath('appData', appData)
process.env.LOCALAPPDATA = path.join(taskRoot, 'local')
const dataDir = path.join(appData, 'skipy-browser', 'skipy-data')
fs.mkdirSync(dataDir, { recursive: true })
fs.writeFileSync(path.join(dataDir, 'library.json'), JSON.stringify({ bookmarks: [], history: [], downloads: [], quickLinks: [], settings: { searchEngine: 'duckduckgo', homepage: 'skipy' } }))
fs.writeFileSync(path.join(dataDir, 'swp.json'), JSON.stringify({ listUpdatedAt: Date.now() }))
app.on('browser-window-created', (_event, win) => win.hide())
let mainWindow, server
const results = []
const pause = ms => new Promise(resolve => setTimeout(resolve, ms))
async function until(fn, label, ms = 12000) {
  const start = Date.now()
  while (Date.now() - start < ms) { const value = await fn(); if (value) return value; await pause(50) }
  throw new Error(`Timeout: ${label}`)
}
const chrome = async (action, value) => {
  const result = await mainWindow.webContents.executeJavaScript(`(async()=>{const value=await window.browser.command(${JSON.stringify(action)},${JSON.stringify(value)});return value===undefined?'__SKIPY_UNDEFINED__':JSON.stringify(value)})()`)
  return result === '__SKIPY_UNDEFINED__' ? undefined : JSON.parse(result)
}
let sdtContents
const sdt = (action, payload) => sdtContents.executeJavaScript(`window.sdt.command(${JSON.stringify(action)},${JSON.stringify(payload)})`)
const state = () => sdtContents.executeJavaScript('window.__sdtState')
function passed(message) { results.push(message); console.log(`PASS ${message}`) }
async function run() {
  server = http.createServer((req, res) => {
    if (req.url === '/echo') {
      let body = ''; req.on('data', chunk => { body += chunk }); req.on('end', () => { res.setHeader('Content-Type', 'application/json'); res.end(JSON.stringify({ method: req.method, headers: req.headers, body })) }); return
    }
    if (req.url === '/slow') { setTimeout(() => { if (!res.destroyed) res.end('slow') }, 1500); return }
    res.setHeader('Content-Type', 'text/html; charset=utf-8')
    res.end(`<!doctype html><html><head><title>SDT próbaoldal</title><style>body{background:#111;color:#eee;font:16px Segoe UI;padding:36px}#color{background:rgb(20,40,60);color:rgb(240,220,200);border:3px solid rgba(255,102,0,.5);width:240px;padding:24px}input,button,a{display:block;margin:20px 0;padding:12px}#click{margin-top:28px}</style></head><body><h1>SDT próbaoldal</h1><div id="color">Színminta</div><input id="name" aria-label="Név"><input id="secret" type="password" aria-label="Jelszó"><button id="click">Kattintás</button><p id="count">0</p><a id="route" href="/second">Második útvonal</a>${req.url === '/second' ? '<button id="second-click">Második oldal művelete</button>' : ''}<script>document.querySelector('#click').onclick=()=>{document.querySelector('#count').textContent=String(Number(document.querySelector('#count').textContent)+1)};</script></body></html>`)
  })
  await new Promise(resolve => server.listen(0, '127.0.0.1', resolve))
  const base = `http://127.0.0.1:${server.address().port}`
  require('../dist-main/main.js')
  mainWindow = await until(() => BrowserWindow.getAllWindows().find(win => win.webContents.getURL().includes('index.html')), 'main window')
  await until(() => mainWindow.webContents.executeJavaScript('!!window.browser').catch(() => false), 'chrome bridge')
  await until(() => mainWindow.webContents.executeJavaScript("document.activeElement?.id==='address'").catch(() => false), 'startup address focus')
  const initial = await chrome('state')
  assert.equal(initial.library.settings.developerMode, false)
  assert.equal(initial.library.settings.searchEngine, 'duckduckgo')
  assert.equal(initial.library.settings.onboardingComplete, false)
  await until(() => mainWindow.webContents.executeJavaScript("!document.getElementById('onboarding').hidden").catch(() => false), 'onboarding visible')
  await chrome('onboarding-complete')
  await until(async () => (await chrome('state')).library.settings.onboardingComplete, 'onboarding completed')
  await until(() => mainWindow.webContents.executeJavaScript("document.getElementById('onboarding').hidden").catch(() => false), 'onboarding hidden')
  assert.equal(await mainWindow.webContents.executeJavaScript("getComputedStyle(document.getElementById('show-sdt')).display"), 'none')
  await chrome('sdt-toggle')
  assert.equal((await chrome('state')).sdtOpen, false)
  passed('Old profile migration; developer mode and SDT hidden by default')

  await chrome('panel', 'settings')
  const settings = await until(() => webContents.getAllWebContents().find(wc => wc.getURL().includes('overlay=panel')), 'settings overlay')
  await until(() => settings.executeJavaScript("!!document.querySelector('input[type=checkbox]')").catch(() => false), 'developer toggle')
  await settings.executeJavaScript("void window.browser.command('settings-developer','on'); true")
  await until(async () => (await chrome('state')).library.settings.developerMode, 'developer enabled')
  await chrome('panel', 'close')
  await chrome('navigate', base)
  const page = await until(() => webContents.getAllWebContents().find(wc => wc.getURL() === base + '/'), 'test page')
  await until(() => !page.isLoadingMainFrame(), 'page loaded')
  assert.equal(await page.executeJavaScript('typeof window.sdt'), 'undefined')
  assert.equal(await page.executeJavaScript('typeof window.browser'), 'undefined')
  const clipboardBefore = await clipboard.readText()
  await chrome('copy-current-url')
  assert.equal(await clipboard.readText(), base + '/')
  await clipboard.writeText(clipboardBefore)
  passed('Startup focuses the address field and the copy button copies the active URL')
  const normalSize = mainWindow.getSize()
  mainWindow.setSize(590, 494)
  await pause(100)
  await chrome('tool', JSON.stringify({ kind: 'certificate', anchor: { x: 140, y: 29, width: 24, height: 24 } }))
  const toolOverlay = await until(() => webContents.getAllWebContents().find(wc => wc.getURL().includes('overlay=tool')), 'certificate tool overlay')
  await until(() => toolOverlay.executeJavaScript("!document.getElementById('tool-popover').hidden").catch(() => false), 'certificate popup rendered')
  const overlayBackgrounds = await toolOverlay.executeJavaScript("[getComputedStyle(document.documentElement).backgroundColor,getComputedStyle(document.body).backgroundColor]")
  assert.deepEqual(overlayBackgrounds, ['rgba(0, 0, 0, 0)', 'rgba(0, 0, 0, 0)'])
  await pause(150)
  const toolShot = await toolOverlay.capturePage().catch(() => null)
  fs.mkdirSync(path.join(__dirname, '..', 'release'), { recursive: true })
  if (toolShot) fs.writeFileSync(path.join(__dirname, '..', 'release', 'tool-overlay-smoke.png'), toolShot.toPNG())
  await toolOverlay.executeJavaScript("void window.browser.command('tool-close'); true")
  mainWindow.setSize(...normalSize)
  await pause(100)
  passed('Floating tool cards keep transparent corners and fit a narrow window')
  const pageHeightBeforeSuggestions = await page.executeJavaScript('innerHeight')
  await mainWindow.webContents.executeJavaScript(`const input=document.getElementById('address');input.focus();input.value=${JSON.stringify(base + '/floating')};input.dispatchEvent(new Event('input',{bubbles:true}));true`)
  const suggestions = await until(() => webContents.getAllWebContents().find(wc => wc.getURL().endsWith('/suggestions.html')), 'floating suggestions view')
  await until(() => suggestions.executeJavaScript("document.querySelectorAll('button').length>0").catch(() => false), 'suggestions rendered')
  assert.equal(await page.executeJavaScript('innerHeight'), pageHeightBeforeSuggestions)
  const suggestionShot = await suggestions.capturePage().catch(() => null)
  fs.mkdirSync(path.join(__dirname, '..', 'release'), { recursive: true })
  if (suggestionShot) fs.writeFileSync(path.join(__dirname, '..', 'release', 'suggestions-smoke.png'), suggestionShot.toPNG())
  await suggestions.executeJavaScript("document.querySelector('button').dispatchEvent(new PointerEvent('pointerdown',{bubbles:true}));true")
  await until(() => page.getURL() === base + '/floating' && !page.isLoadingMainFrame(), 'suggestion navigation')
  await chrome('navigate', base)
  await until(() => page.getURL() === base + '/' && !page.isLoadingMainFrame(), 'return after suggestion navigation')
  passed('Address suggestions float above the page without resizing it')
  await chrome('sdt-toggle')
  sdtContents = await until(() => webContents.getAllWebContents().find(wc => wc.getURL().endsWith('/sdt.html')), 'SDT renderer')
  await until(() => sdtContents.executeJavaScript('!!window.sdt').catch(() => false), 'SDT bridge')
  await sdtContents.executeJavaScript('void window.sdt.onState(s=>{window.__sdtState=s}); true')
  await sdt('state')
  await until(async () => (await state())?.site === '127.0.0.1', 'active target')
  passed('Settings toggle, dedicated SDT view, website has no SDT IPC')

  await session.defaultSession.cookies.set({ url: base, name: 'browser-secret', value: 'must-not-leak' })
  assert.equal((await sdt('api-send', { url: base + '/echo', method: 'POST', headers: [{ name: 'X-Sdt', value: 'ok' }], body: '{"hello":"world"}', bodyType: 'json' })).ok, true)
  let done = await until(async () => { const s = await state(); return s && !s.apiRunning && s.apiResult ? s : null }, 'API result')
  const echo = JSON.parse(done.apiResult.body)
  assert.equal(echo.headers['x-sdt'], 'ok')
  assert.equal(echo.headers.cookie, undefined)
  assert.equal(echo.body, '{"hello":"world"}')
  passed('POST JSON + custom header with browser cookie isolation')

  const steps = [
    { id: 'url', kind: 'url', value: base + '/' },
    { id: 'type', name: 'Név mező kitöltése', kind: 'input', selector: '#name', value: 'Skipy teszt', expectedValue: 'Skipy teszt' },
    { id: 'wait', kind: 'wait', ms: 50 },
    { id: 'click', kind: 'click', selector: '#click', x: 40, y: 40 },
  ]
  assert.equal((await sdt('test-save', { name: 'SDT próba', steps })).ok, true)
  await until(async () => (await state()).tests.length === 1, 'saved test')
  await sdtContents.executeJavaScript(`(()=>{document.getElementById('tab-tests').click();const select=document.getElementById('saved-tests');select.value=window.__sdtState.tests[0].id;select.dispatchEvent(new Event('change',{bubbles:true}));return true})()`)
  await until(() => sdtContents.executeJavaScript("document.querySelectorAll('#steps .step').length===4"), 'saved test visible in panel')
  await sdtContents.executeJavaScript("document.getElementById('run').click(); true")
  await until(async () => (await state()).mode === 'running', 'panel Run button acknowledged')
  done = await until(async () => { const s = await state(); return s.mode === 'idle' && s.results.length === steps.length && s.results.every(r => r.status !== 'running') ? s : null }, 'run success')
  assert.ok(done.results.every(r => r.status === 'passed'), JSON.stringify(done.results))
  assert.equal(done.results.find(r=>r.id==='type').name,'Név mező kitöltése')
  assert.equal(await page.executeJavaScript("document.getElementById('name').value"), 'Skipy teszt')
  assert.equal(await page.executeJavaScript("document.getElementById('count').textContent"), '1')
  assert.equal((await sdt('test-run', { steps: [{ id: 'other', kind: 'url', value: 'https://example.com/' }] })).ok, false)
  passed('Actual panel Run button starts and completes the saved UI test')
  passed('Saved UI test replays native input/click and rejects another site')

  const secretPanelSteps = [{ id: 'secret-url', kind: 'url', value: base + '/' }, { id: 'secret-panel', kind: 'input', selector: '#secret', sensitive: true }]
  await sdt('draft-set', secretPanelSteps)
  await until(() => sdtContents.executeJavaScript("document.querySelectorAll('#steps .step').length===2"), 'secret draft visible')
  await sdtContents.executeJavaScript("document.getElementById('run').click(); true")
  await until(() => sdtContents.executeJavaScript("document.getElementById('secret-dialog').open"), 'inline secret dialog')
  await sdtContents.executeJavaScript("document.getElementById('secret-value').value='panel-secret';document.getElementById('secret-confirm').click();true")
  await until(async () => (await state()).mode === 'running', 'secret run acknowledged')
  done = await until(async () => { const s=await state(); return s.mode==='idle'&&s.results.length===2?s:null }, 'secret run complete')
  assert.ok(done.results.every(result=>result.status==='passed'),JSON.stringify(done.results))
  assert.equal(await page.executeJavaScript("document.getElementById('secret').value"),'panel-secret')
  passed('Sensitive fields use the in-panel dialog and start the run visibly')

  await sdt('test-run', { steps: [{ id: 'missing', kind: 'click', selector: '#missing' }] })
  done = await until(async () => { const s = await state(); return s.mode === 'idle' && s.results.some(r => r.status === 'failed') ? s : null }, 'missing element failure')
  passed('Missing element fails with a per-step result')
  const advanced = [
    { id: 'fail-fast', kind: 'click', selector: '#missing', timeoutMs: 200 },
    { id: 'visible', kind: 'assert-visible', selector: '#color', timeoutMs: 500 },
    { id: 'text', kind: 'assert-text', selector: '#color', value: 'Színminta', timeoutMs: 500 },
    { id: 'secret-input', kind: 'input', selector: '#secret', sensitive: true },
    { id: 'key', kind: 'key', value: 'Tab' },
    { id: 'shot', kind: 'screenshot', value: 'állapot' },
  ]
  await sdt('test-run', { name: 'Haladó próba', steps: advanced, secrets: { 'secret-input': 'csak-memória' } })
  done = await until(async () => { const s = await state(); return s.mode === 'idle' && s.results.length === advanced.length && s.runs?.length ? s : null }, 'advanced run')
  assert.equal(done.results.filter(r => r.status === 'failed').length, 1)
  assert.equal(done.results.filter(r => r.status === 'passed').length, advanced.length - 1)
  assert.equal(await page.executeJavaScript("document.getElementById('secret').value"), 'csak-memória')
  assert.ok(done.runs[0].results.some(r => r.screenshot), JSON.stringify(done.runs[0]))
  passed('Assertions, runtime secret, screenshots and continue-after-failure work')
  await sdt('test-run', { steps: [{ id: 'longwait', kind: 'wait', ms: 30000 }] })
  await until(async () => (await state()).mode === 'running', 'wait running')
  await sdt('stop')
  await until(async () => (await state()).mode === 'idle', 'stop running')
  passed('Running UI test stops immediately')

  await sdt('pick-start')
  await until(async () => (await state()).mode === 'picking', 'picking')
  const colorRect = await page.executeJavaScript("JSON.stringify(document.getElementById('color').getBoundingClientRect().toJSON())")
  const rect = JSON.parse(colorRect)
  // CDP produces real trusted input without interacting with the user's desktop.
  await page.debugger.sendCommand('Input.dispatchMouseEvent', { type: 'mouseMoved', x: rect.x + 15, y: rect.y + 15 })
  await page.debugger.sendCommand('Input.dispatchMouseEvent', { type: 'mousePressed', x: rect.x + 15, y: rect.y + 15, button: 'left', clickCount: 1 })
  await page.debugger.sendCommand('Input.dispatchMouseEvent', { type: 'mouseReleased', x: rect.x + 15, y: rect.y + 15, button: 'left', clickCount: 1 })
  done = await until(async () => { const s = await state(); return s.selection ? s : null }, 'picked colors')
  assert.ok(done.selection.colors.some(c => c.hex?.toLowerCase() === '#14283c'), JSON.stringify(done.selection))
  passed('Color picker returns the actual element RGB and HEX')

  await sdt('record-start')
  await until(async () => (await state()).mode === 'recording', 'recording')
  const clickRect = JSON.parse(await page.executeJavaScript("JSON.stringify(document.getElementById('click').getBoundingClientRect().toJSON())"))
  await page.debugger.sendCommand('Input.dispatchMouseEvent', { type: 'mousePressed', x: clickRect.x + 10, y: clickRect.y + 10, button: 'left', clickCount: 1 })
  await page.debugger.sendCommand('Input.dispatchMouseEvent', { type: 'mouseReleased', x: clickRect.x + 10, y: clickRect.y + 10, button: 'left', clickCount: 1 })
  await until(async () => (await state()).draft.some(step => step.kind === 'click'), 'recorded click')
  await sdt('stop')
  assert.ok((await state()).draft.some(step => step.kind === 'click'))
  passed('UI recording captures trusted clicks and retains draft after stopping')

  await sdt('record-start')
  await until(async () => (await state()).mode === 'recording', 'multi-route recording')
  const routeRect = JSON.parse(await page.executeJavaScript("JSON.stringify(document.getElementById('route').getBoundingClientRect().toJSON())"))
  await page.debugger.sendCommand('Input.dispatchMouseEvent', { type: 'mousePressed', x: routeRect.x + 10, y: routeRect.y + 10, button: 'left', clickCount: 1 })
  await page.debugger.sendCommand('Input.dispatchMouseEvent', { type: 'mouseReleased', x: routeRect.x + 10, y: routeRect.y + 10, button: 'left', clickCount: 1 })
  await until(() => page.getURL() === base + '/second' && !page.isLoadingMainFrame(), 'second route loaded')
  done = await until(async () => { const value = await state(); return value.mode === 'recording' && value.draft.some(step => step.kind === 'url' && step.value === base + '/second') ? value : null }, 'route recording resumed')
  const secondRect = JSON.parse(await page.executeJavaScript("JSON.stringify(document.getElementById('second-click').getBoundingClientRect().toJSON())"))
  await page.debugger.sendCommand('Input.dispatchMouseEvent', { type: 'mousePressed', x: secondRect.x + 10, y: secondRect.y + 10, button: 'left', clickCount: 1 })
  await page.debugger.sendCommand('Input.dispatchMouseEvent', { type: 'mouseReleased', x: secondRect.x + 10, y: secondRect.y + 10, button: 'left', clickCount: 1 })
  done = await until(async () => { const value = await state(); return value.draft.some(step => step.kind === 'click' && step.selector === '#second-click') ? value : null }, 'recording continued on second route')
  await sdt('stop')
  const routeSteps = done.draft
  assert.ok(routeSteps.some(step => step.kind === 'click' && step.selector === '#route'), JSON.stringify(routeSteps))
  assert.ok(routeSteps.some(step => step.kind === 'click' && step.selector === '#second-click'), JSON.stringify(routeSteps))
  assert.equal(page.getURL(), base + '/second')
  await sdt('test-run', { steps: routeSteps })
  done = await until(async () => { const value = await state(); return value.mode === 'idle' && value.results.length === routeSteps.length && value.results.every(result => result.status !== 'running') ? value : null }, 'multi-route replay', 25000)
  assert.ok(done.results.every(result => result.status === 'passed'), JSON.stringify(done.results))
  assert.equal(page.getURL(), base + '/second')
  passed('A UI test opens its starting URL, then replays multiple routes on the same site')

  await chrome('navigate', base)
  await until(() => page.getURL() === base + '/' && !page.isLoadingMainFrame(), 'return before cancellation')
  await sdt('record-start')
  await chrome('navigate', base + '/second')
  await until(async () => (await state()).mode === 'idle', 'navigation cancellation')
  await until(() => !page.isLoadingMainFrame(), 'second loaded')
  await sdt('api-send', { url: base + '/slow', method: 'GET', headers: [], body: '', bodyType: 'text' })
  await chrome('settings-developer', 'off')
  assert.equal((await sdt('pick-start')).ok, false)
  await until(async () => !(await chrome('state')).sdtOpen, 'SDT closed')
  assert.equal((await chrome('state')).library.settings.developerMode, false)
  passed('Toolbar navigation cancels recording; disabling closes SDT and rejects its IPC')
  await chrome('settings-developer', 'on')
  await chrome('sdt-toggle')
  await sdt('state')
  await until(async () => (await state()).tests.length === 1, 'saved test retained')
  await pause(250)
  assert.equal(JSON.parse(fs.readFileSync(path.join(dataDir, 'library.json'), 'utf8')).settings.developerMode, true)
  const saved = JSON.parse(fs.readFileSync(path.join(dataDir, 'sdt.json'), 'utf8'))
  assert.equal(saved.tests.length, 1)
  passed('Developer setting and test persisted; disabling does not delete saved tests')
  mainWindow.setSize(740, 600)
  await pause(100)
  const shot = await sdtContents.capturePage().catch(() => null)
  fs.mkdirSync(path.join(__dirname, '..', 'release'), { recursive: true })
  if (shot) fs.writeFileSync(path.join(__dirname, '..', 'release', 'sdt-smoke.png'), shot.toPNG())
  fs.writeFileSync(path.join(__dirname, '..', 'release', 'sdt-smoke-results.json'), JSON.stringify({ passed: results, profile: taskRoot }, null, 2))
  console.log(`SDT_SMOKE_OK ${results.length} cases; isolated profile ${taskRoot}`)
}
const watchdog = setTimeout(() => { console.error('Smoke test exceeded 90 seconds'); app.exit(1) }, 90000)
run().then(() => { clearTimeout(watchdog); server.close(); app.quit() }).catch(error => { clearTimeout(watchdog); console.error(error); console.error(`Isolated test profile: ${taskRoot}`); server?.close(); app.exit(1) })
