import './style.css'
import { createIcons, X, Download, Globe, Shield } from 'lucide'

type Entry = { id:string; title?:string; name?:string; url:string; path?:string; enabled?:boolean; favicon?:string; createdAt?:number; visitedAt?:number; startedAt?:number; folder?:string; received?:number; total?:number; status?:'progressing'|'paused'|'completed'|'cancelled'|'interrupted' }
type Privacy = { site:string; protection:'active'|'error'|'pending'; fingerprintEnabled:boolean; blockedHosts:string[]; rows:{host:string;count:number;blocked:number;lastSeen:number;blockedNow:boolean}[] }
type State = { activeId:string; defaultBrowser:boolean; privateMode?:boolean; globalBassDb:number; globalBassFrequency:number; toolPopover:'certificate'|'bass'|null; certificate:any; pageSafety:{level:string;title:string;reasons:string[]}; panel:'bookmarks'|'history'|'downloads'|'settings'|'privacy'|'extensions'|null; pendingDownload:{id:string;filename:string;host:string;total:number}|null; jsDialog:{id:string;tabId:string;type:'alert'|'confirm'|'prompt'|'beforeunload';message:string;defaultPrompt:string;host:string}|null; swpPrompt:{id:string;kind:'permission'|'popup'|'clear-data';site:string;permission?:string;target?:string}|null; swp:any; tabs:{id:string;bassStatus:string}[]; privacy:Privacy|null; library:{bookmarks:Entry[];history:Entry[];downloads:Entry[];extensions:Entry[];settings:{searchEngine:string;homepage:string;developerMode:boolean;onboardingComplete:boolean;autoHibernateMinutes:number}} }
const browser=(window as unknown as {browser:{command:(action:string,value?:string)=>Promise<State|string|void>;onState:(callback:(state:State)=>void)=>()=>void;onOverlayClose:(callback:()=>void)=>()=>void}}).browser
const $=(id:string)=>document.getElementById(id)!
const mode=new URLSearchParams(location.search).get('overlay')
// WebContentsView transparency must be applied to the root element as well.
// A transparent body alone still exposes the opaque :root background around
// rounded cards, which appears as a large black rectangle over the page.
document.documentElement.classList.add('overlay-root')
document.body.classList.add(`overlay-${mode}`)
let state:State
let lastSignature=''
let lastPanel:State['panel']=null
let overlayClosing=false
const command=(action:string,value?:string)=>void browser.command(action,value)
function formatBytes(bytes:number){return bytes<1024?`${bytes} B`:bytes<1048576?`${(bytes/1024).toFixed(1)} KB`:`${(bytes/1048576).toFixed(1)} MB`}
function action(label:string,name:string,value?:string){const b=document.createElement('button');b.className='row-action';b.textContent=label;b.onclick=()=>command(name,value);return b}
function favicon(url?:string){const w=document.createElement('span');w.className='favicon-wrap';const fallback=document.createElement('span');fallback.innerHTML='<i data-lucide="globe"></i>';w.append(fallback);if(url){const img=document.createElement('img');img.hidden=true;img.onload=()=>{img.hidden=false;fallback.hidden=true};img.onerror=()=>img.remove();img.src=url;w.append(img)}return w}
function renderSettings(list:HTMLElement){
  const developer=document.createElement('label');developer.className='developer-setting'
  const toggle=document.createElement('input');toggle.type='checkbox';toggle.checked=!!state.library.settings.developerMode
  toggle.onchange=()=>command('settings-developer',toggle.checked?'on':'off')
  const text=document.createElement('span');text.textContent='I am a developer'
  const help=document.createElement('small');help.textContent='SDT · színválasztó, API és UI-tesztek';text.append(help);developer.append(toggle,text);list.append(developer)
  const search=document.createElement('select');for(const name of ['google','duckduckgo','bing']){const o=document.createElement('option');o.value=name;o.textContent=name==='duckduckgo'?'DuckDuckGo':name[0].toUpperCase()+name.slice(1);search.append(o)}search.value=state.library.settings.searchEngine;search.onchange=()=>command('settings-search',search.value);const l=document.createElement('label');l.className='setting-field';l.append('Címsori kereső',search);list.append(l);const form=document.createElement('form');form.className='setting-form';const input=document.createElement('input');input.placeholder='skipy vagy https://pelda.hu/';input.value=state.library.settings.homepage;const save=document.createElement('button');save.textContent='Mentés';form.append(input,save);form.onsubmit=e=>{e.preventDefault();void browser.command('settings-home',input.value)};list.append(form)
}
function renderDataSettings(list:HTMLElement){const sleepLabel=document.createElement('label');sleepLabel.className='setting-field';const sleep=document.createElement('select');for(const [value,label] of [['0','Kikapcsolva'],['5','5 perc'],['15','15 perc'],['30','30 perc'],['60','60 perc']]){const option=document.createElement('option');option.value=value;option.textContent=label;sleep.append(option)}sleep.value=String(state.library.settings.autoHibernateMinutes??15);sleep.onchange=()=>command('settings-hibernation',sleep.value);sleepLabel.append('Automatikus laphibernálás',sleep);list.append(sleepLabel);if(!state.privateMode){const browserTitle=document.createElement('h3');browserTitle.className='settings-section-title';browserTitle.textContent='Alapértelmezett böngésző';const browserCard=document.createElement('div');browserCard.className='default-browser-card';const copy=document.createElement('span');const strong=document.createElement('strong');strong.textContent=state.defaultBrowser?'A Skipy az alapértelmezett':'A Skipy nem alapértelmezett';const small=document.createElement('small');small.textContent='HTTP és HTTPS hivatkozások megnyitása';copy.append(strong,small);const setDefault=action(state.defaultBrowser?'Beállítva':'Beállítás','settings-default-browser');setDefault.disabled=state.defaultBrowser;browserCard.append(copy,setDefault);list.append(browserTitle,browserCard)}const title=document.createElement('h3');title.className='settings-section-title';title.textContent='Import, export és visszaállítás';const buttons=document.createElement('div');buttons.className='settings-data-actions';buttons.append(action('Import másik böngészőből','browser-import'),action('Könyvjelzők exportálása','bookmarks-export'),action('Skipy biztonsági mentés','backup-export'));const reset=action('Teljes reset','browser-reset');reset.classList.add('danger-action');buttons.append(reset);list.append(title,buttons)}
function renderPrivacy(list:HTMLElement,actions:HTMLElement){const p=state.privacy;if(!p){list.innerHTML='<p class="panel-empty">Nyiss meg egy weboldalt a kérésfigyelőhöz.</p>';return}const site=document.createElement('div');site.className='privacy-site';site.textContent=`Webhely: ${p.site}`;list.append(site);const protection=document.createElement('div');protection.className='privacy-protection';protection.append(`${p.fingerprintEnabled?'Ujjlenyomat-védelem':'Védelem kikapcsolva'} · ${p.protection}`,action(p.fingerprintEnabled?'Kikapcsolás':'Bekapcsolás','privacy-fingerprint',p.fingerprintEnabled?'off':'on'));list.append(protection);actions.append(action('Webhely naplójának törlése','privacy-clear-site'),action('Összes napló törlése','privacy-clear-all'));const rows=[...p.rows];for(const host of p.blockedHosts)if(!rows.some(r=>r.host===host))rows.push({host,count:0,blocked:0,lastSeen:0,blockedNow:true});for(const row of rows){const item=document.createElement('div');item.className='library-row';const title=document.createElement('div');title.className='row-title';title.textContent=row.host;const sub=document.createElement('div');sub.className='row-subtitle';sub.textContent=`${row.count} kérés · ${row.blocked} tiltva`;item.append(title,sub,action(row.blockedNow?'Feloldás':'Letiltás','privacy-block',row.host));list.append(item)}}
function renderSwp(list:HTMLElement,actions:HTMLElement){const p=state.privacy,s=state.swp;if(!p||!s){list.innerHTML='<p class="panel-empty">Nyiss meg egy weboldalt az SWP használatához.</p>';return}const site=document.createElement('div');site.className='privacy-site';site.innerHTML=`<strong>SWP · Skipy Web Protect</strong><br>${p.site}`;list.append(site);const card=(title:string,text:string,button?:HTMLElement)=>{const d=document.createElement('div');d.className='privacy-protection';const copy=document.createElement('span');const strong=document.createElement('strong');strong.textContent=title;copy.append(strong,document.createElement('br'),text);d.append(copy);if(button)d.append(button);list.append(d)};card('Reklám- és követésblokkolás',`${s.adblock?'Aktív':'Kikapcsolva'} · ${s.blockedSite} blokkolva`,action(s.adblock?'Kikapcsolás':'Bekapcsolás','swp-adblock'));card('Ujjlenyomat-védelem',`${p.fingerprintEnabled?'Aktív':'Kikapcsolva'} · ${p.protection}`,action(p.fingerprintEnabled?'Kikapcsolás':'Bekapcsolás','privacy-fingerprint',p.fingerprintEnabled?'off':'on'));card('Szűrőlisták',`${s.listStatus==='updated'?new Date(s.listUpdatedAt).toLocaleDateString('hu-HU'):s.listStatus==='error'?'Frissítési hiba · tartalék lista aktív':'Beépített lista'} · ${s.blockedTotal} blokkolás`,action('Frissítés','swp-update-lists'));const names:any={camera:'Kamera',microphone:'Mikrofon',notifications:'Értesítés'};for(const key of Object.keys(names)){const value=s.permissions[key];card(names[key],value==='allow'?'Mindig engedélyezve':value==='block'?'Mindig tiltva':'Mindig kérdez',value?action('Alaphelyzet','swp-permission-reset',key):undefined)}card('Felugró ablakok',s.popup==='allow'?'Mindig engedélyezve':s.popup==='block'?'Mindig tiltva':`Mindig kérdez · ${s.popupBlockedTotal} blokkolva`,s.popup?action('Alaphelyzet','swp-popup-reset'):undefined);card('Helyi webhelyadatok',`${s.storage.cookies} cookie · ${formatBytes(s.storage.bytes||0)}`,action('Törlés','swp-clear-site'));card('Törlés kilépéskor',s.clearOnExit?'Bekapcsolva':'Kikapcsolva',action(s.clearOnExit?'Kikapcsolás':'Bekapcsolás','swp-clear-on-exit'));actions.append(action('Minden webhelyadat törlése','swp-clear-all'),action('Kérésnapló törlése','privacy-clear-site'));const h=document.createElement('h3');h.className='privacy-heading';h.textContent='Élő kérésfigyelő';list.append(h);renderPrivacyRows(p,list)}
function renderPrivacyRows(p:Privacy,list:HTMLElement){const rows=[...p.rows];for(const host of p.blockedHosts)if(!rows.some(r=>r.host===host))rows.push({host,count:0,blocked:0,lastSeen:0,blockedNow:true});for(const row of rows){const item=document.createElement('div');item.className='library-row';const title=document.createElement('div');title.className='row-title';title.textContent=row.host;const sub=document.createElement('div');sub.className='row-subtitle';sub.textContent=`${row.count} kérés · ${row.blocked} tiltva`;item.append(title,sub,action(row.blockedNow?'Feloldás':'Letiltás','privacy-block',row.host));list.append(item)}}
function renderBookmarks(list:HTMLElement){const search=document.createElement('input');search.className='bookmark-search';search.placeholder='Keresés a könyvjelzők között…';const results=document.createElement('div');list.append(search,results);const draw=()=>{results.replaceChildren();const query=search.value.trim().toLocaleLowerCase('hu-HU');const entries=state.library.bookmarks.filter(entry=>!query||(entry.title||'').toLocaleLowerCase('hu-HU').includes(query)||entry.url.toLowerCase().includes(query)||(entry.folder||'Kedvencek').toLocaleLowerCase('hu-HU').includes(query));if(!entries.length){const empty=document.createElement('p');empty.className='panel-empty';empty.textContent='Nincs találat.';results.append(empty);return}const groups=new Map<string,Entry[]>();for(const entry of entries){const folder=entry.folder||'Kedvencek';const group=groups.get(folder)||[];group.push(entry);groups.set(folder,group)}for(const [folder,items] of groups){const heading=document.createElement('div');heading.className='bookmark-group';heading.textContent=folder;results.append(heading);for(const entry of items){const row=document.createElement('div');row.className='library-row';if(entry.favicon)row.append(favicon(entry.favicon));const title=document.createElement('div');title.className='row-title';title.textContent=entry.title||entry.url;const url=document.createElement('div');url.className='row-subtitle';url.textContent=entry.url;const folderInput=document.createElement('input');folderInput.className='bookmark-folder-input';folderInput.value=folder;folderInput.placeholder='Mappa';folderInput.onchange=()=>command('bookmark-folder',JSON.stringify({id:entry.id,folder:folderInput.value}));const footer=document.createElement('div');footer.className='row-footer';footer.append(action('Megnyitás','open-entry',entry.id),action('Törlés','bookmark-remove',entry.id));row.append(title,url,folderInput,footer);results.append(row)}}};search.oninput=draw;draw()}

function renderDownloads(list:HTMLElement,actions:HTMLElement){
  const entries=[...state.library.downloads].sort((a,b)=>(b.startedAt||0)-(a.startedAt||0))
  const active=entries.filter(e=>e.status==='progressing'||e.status==='paused').length
  const summary=document.createElement('div');summary.className='download-history-summary';summary.innerHTML=`<strong>${active?`${active} aktív letöltés`:'Letöltési előzmények'}</strong><span>${entries.length} elem</span>`;list.append(summary)
  if(entries.some(e=>e.status!=='progressing'&&e.status!=='paused'))actions.append(action('Befejezettek törlése','downloads-clear-finished'))
  if(!entries.length){const empty=document.createElement('p');empty.className='panel-empty';empty.textContent='Még nincs letöltési előzmény.';list.append(empty);return}
  const labels:Record<string,string>={progressing:'Letöltés',paused:'Szüneteltetve',completed:'Kész',cancelled:'Megszakítva',interrupted:'Sikertelen'}
  for(const e of entries){
    const percent=e.total?Math.min(100,Math.round((e.received||0)/e.total*100)):0
    const row=document.createElement('article');row.className=`library-row download-card ${e.status}`
    const head=document.createElement('div');head.className='download-card-head'
    const icon=document.createElement('span');icon.className='download-file-icon';icon.innerHTML='<i data-lucide="download"></i>'
    const copy=document.createElement('div');copy.className='download-card-copy'
    const title=document.createElement('div');title.className='row-title';title.textContent=e.name||'Ismeretlen fájl';title.title=e.name||''
    const source=document.createElement('div');source.className='row-subtitle';try{source.textContent=new URL(e.url).hostname}catch{source.textContent=e.url||''}
    copy.append(title,source)
    const status=document.createElement('span');status.className='download-status';status.textContent=labels[e.status||'']||''
    head.append(icon,copy,status);row.append(head)
    if(e.status==='progressing'||e.status==='paused'){
      const progress=document.createElement('div');progress.className='download-item-progress';progress.style.setProperty('--item-progress',`${percent}%`);progress.setAttribute('role','progressbar');progress.setAttribute('aria-valuenow',String(percent));row.append(progress)
    }
    const meta=document.createElement('div');meta.className='download-card-meta'
    const amount=e.total?`${formatBytes(e.received||0)} / ${formatBytes(e.total)} · ${percent}%`:formatBytes(e.received||0)
    const date=e.startedAt?new Date(e.startedAt).toLocaleString('hu-HU',{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'}):''
    meta.append(Object.assign(document.createElement('span'),{textContent:amount}),Object.assign(document.createElement('span'),{textContent:date}));row.append(meta)
    const footer=document.createElement('div');footer.className='row-footer'
    if(e.status==='progressing')footer.append(action('Szünet','download-pause',e.id),action('Megszakítás','download-cancel',e.id))
    else if(e.status==='paused')footer.append(action('Folytatás','download-resume',e.id),action('Megszakítás','download-cancel',e.id))
    else{if(e.status==='completed'){const open=action('Megnyitás','download-reveal',e.id);open.classList.add('primary-download-action');footer.append(open)}footer.append(action('Eltávolítás','download-remove',e.id))}
    row.append(footer);list.append(row)
  }
}

function renderExtensions(list:HTMLElement,actions:HTMLElement){
  const installer=document.createElement('form');installer.className='extension-installer';const title=document.createElement('strong');title.textContent='Telepítés a Chrome Web Store-ból';const help=document.createElement('p');help.textContent='Másold be a bővítmény Web Store-linkjét vagy azonosítóját.';const field=document.createElement('div');const input=document.createElement('input');input.placeholder='https://chromewebstore.google.com/detail/…';input.required=true;const submit=document.createElement('button');submit.type='submit';submit.textContent='Telepítés';field.append(input,submit);const result=document.createElement('small');installer.append(title,help,field,result)
  installer.onsubmit=async event=>{event.preventDefault();submit.disabled=true;submit.textContent='Letöltés…';result.textContent='';const response=await browser.command('extension-store-install',input.value);if(typeof response==='string'){result.textContent=response;result.className='extension-error'}else input.value='';submit.disabled=false;submit.textContent='Telepítés'};list.append(installer)
  actions.append(action('Kicsomagolt mappa betöltése','extension-add'));if(!state.library.extensions.length){const empty=document.createElement('p');empty.className='panel-empty';empty.textContent='Nincs telepített bővítmény.';list.append(empty);return}const note=document.createElement('p');note.className='extension-compatibility';note.textContent='Egyes Chrome bővítmények az Electron korlátozásai miatt csak részben működnek.';list.append(note)
  for(const e of state.library.extensions){const row=document.createElement('div');row.className='library-row';const rowTitle=document.createElement('div');rowTitle.className='row-title';rowTitle.textContent=e.name||'Bővítmény';const sub=document.createElement('div');sub.className='row-subtitle';sub.textContent=e.enabled?'Aktív':'Kikapcsolva';const foot=document.createElement('div');foot.className='row-footer';foot.append(action(e.enabled?'Kikapcsolás':'Bekapcsolás','extension-toggle',e.id),action('Eltávolítás','extension-remove',e.id));row.append(rowTitle,sub,foot);list.append(row)}
}function renderPanel(){const panel=$('library-panel'),list=$('panel-list'),actions=$('panel-actions');panel.hidden=!state.panel;list.replaceChildren();actions.replaceChildren();if(!state.panel)return;const labels:any={bookmarks:'Könyvjelzők',history:'Előzmények',downloads:'Letöltések',settings:'Beállítások',privacy:'SWP',extensions:'Bővítmények'};$('panel-title').textContent=labels[state.panel];if(state.panel==='downloads'){renderDownloads(list,actions);createIcons({icons:{Download}});return}if(state.panel==='settings'){renderSettings(list);renderDataSettings(list);return}if(state.panel==='privacy'){renderSwp(list,actions);return}if(state.panel==='extensions'){renderExtensions(list,actions);return}if(false){actions.append(action('Kicsomagolt bővítmény betöltése','extension-add'));if(!state.library.extensions.length){list.innerHTML='<p class="panel-empty">Nincs telepített bővítmény.</p>';return}for(const e of state.library.extensions){const row=document.createElement('div');row.className='library-row';const title=document.createElement('div');title.className='row-title';title.textContent=e.name||'Bővítmény';const sub=document.createElement('div');sub.className='row-subtitle';sub.textContent=e.enabled?'Aktív':'Kikapcsolva';const foot=document.createElement('div');foot.className='row-footer';foot.append(action(e.enabled?'Kikapcsolás':'Bekapcsolás','extension-toggle',e.id),action('Eltávolítás','extension-remove',e.id));row.append(title,sub,foot);list.append(row)}return}if(state.panel==='bookmarks'){renderBookmarks(list);return}if(state.panel==='history'&&state.library.history.length)actions.append(action('Összes előzmény törlése','history-clear'));const entries=state.library[state.panel] as Entry[];if(!entries.length){list.innerHTML='<p class="panel-empty">A lista üres.</p>';return}for(const e of entries){const row=document.createElement('div');row.className='library-row';const title=document.createElement('div');title.className='row-title';title.textContent=e.name||e.title||e.url;const sub=document.createElement('div');sub.className='row-subtitle';sub.textContent=e.url;const foot=document.createElement('div');foot.className='row-footer';foot.append(action('Megnyitás','open-entry',e.id),action('Törlés',e.visitedAt?'history-remove':'bookmark-remove',e.id));if(e.favicon)row.append(favicon(e.favicon));row.append(title,sub,foot);list.append(row)}createIcons({icons:{Globe}})}
function renderTool(){const root=$('tool-popover');root.hidden=!state.toolPopover;root.replaceChildren();if(!state.toolPopover)return;const h=document.createElement('div');h.className='tool-popover-heading';h.innerHTML=`<strong>${state.toolPopover==='certificate'?'Kapcsolat és tanúsítvány':'Bass Booster'}</strong>`;h.append(action('×','tool-close'));root.append(h);if(state.toolPopover==='certificate'){const safety=document.createElement('div');safety.className='safety-card '+state.pageSafety.level;const safetyTitle=document.createElement('strong');safetyTitle.textContent=state.pageSafety.title;const safetyList=document.createElement('ul');for(const reason of state.pageSafety.reasons){const item=document.createElement('li');item.textContent=reason;safetyList.append(item)}safety.append(safetyTitle,safetyList);root.append(safety);const c=state.certificate;const p=document.createElement('p');p.className=`certificate-status ${c.status}`;p.textContent=c.status==='secure'?'A kapcsolat tanúsítványa érvényes.':c.status==='error'?`Tanúsítványhiba: ${c.error||'ismeretlen'}`:c.status==='loading'?'Betöltés…':'Nincs elérhető HTTPS-tanúsítvány.';root.append(p);for(const [label,value] of [['Webhely',c.host],['Alany',c.subject],['Kibocsátó',c.issuer],['Érvényes ettől',c.validFrom?new Date(c.validFrom*1000).toLocaleString('hu-HU'):undefined],['Érvényes eddig',c.validTo?new Date(c.validTo*1000).toLocaleString('hu-HU'):undefined],['Protokoll',c.protocol],['Titkosítás',c.cipher]])if(value){const r=document.createElement('div');r.className='certificate-field';r.innerHTML=`<span>${label}</span><strong></strong>`;(r.lastElementChild as HTMLElement).textContent=String(value);root.append(r)}}else{const presets=document.createElement('div');presets.className='bass-presets';for(const [name,db,f] of [['Tiszta',4,80],['Mély',7,95],['Erős',10,120]] as const){const b=document.createElement('button');b.textContent=name;b.onclick=()=>command('bass-set',JSON.stringify({db,frequency:f}));presets.append(b)}root.append(presets);for(const cfg of [{label:'Erősség',min:0,max:12,step:1,value:state.globalBassDb,key:'db'},{label:'Basszusfrekvencia',min:60,max:160,step:5,value:state.globalBassFrequency,key:'frequency'}]){const l=document.createElement('label');l.className='bass-control';const s=document.createElement('span');s.textContent=`${cfg.label} · ${cfg.value}${cfg.key==='db'?' dB':' Hz'}`;const input=document.createElement('input');input.type='range';input.min=String(cfg.min);input.max=String(cfg.max);input.step=String(cfg.step);input.value=String(cfg.value);input.oninput=()=>s.textContent=`${cfg.label} · ${input.value}${cfg.key==='db'?' dB':' Hz'}`;input.onchange=()=>command('bass-set',JSON.stringify({db:cfg.key==='db'?Number(input.value):state.globalBassDb,frequency:cfg.key==='frequency'?Number(input.value):state.globalBassFrequency}));l.append(s,input);root.append(l)}}}
function renderConfirm(){const p=state.pendingDownload,root=$('download-confirm');root.hidden=!p;if(!p)return;$('download-confirm-name').textContent=p.filename;$('download-confirm-meta').textContent=`${p.host} · ${p.total>0?formatBytes(p.total):'ismeretlen méret'}`;($('download-confirm-accept') as HTMLButtonElement).dataset.id=p.id;($('download-confirm-custom') as HTMLButtonElement).dataset.id=p.id;($('download-confirm-cancel') as HTMLButtonElement).dataset.id=p.id}
function answerDialog(accept:boolean){const d=state.jsDialog;if(!d)return;command('js-dialog-answer',JSON.stringify({id:d.id,accept,promptText:($('js-dialog-input') as HTMLInputElement).value}))}
function renderJsDialog(){const d=state.jsDialog,root=$('js-dialog');root.hidden=!d;if(!d)return;$('js-dialog-host').textContent=d.host;$('js-dialog-title').textContent=d.type==='alert'?'A weboldal üzenete':d.type==='prompt'?'A weboldal választ kér':d.type==='beforeunload'?'Elhagyod ezt az oldalt?':'A weboldal megerősítést kér';$('js-dialog-message').textContent=d.message||'A weboldal nem adott meg üzenetet.';const input=$('js-dialog-input') as HTMLInputElement;input.hidden=d.type!=='prompt';input.value=d.defaultPrompt;$('js-dialog-cancel').hidden=d.type==='alert';requestAnimationFrame(()=>d.type==='prompt'?input.focus():($('js-dialog-accept') as HTMLButtonElement).focus())}
function renderSwpPrompt(){const p=state.swpPrompt,root=$('swp-prompt');root.hidden=!p;if(!p)return;$('swp-prompt-site').textContent=p.site;if(p.kind==='popup'){$('swp-prompt-title').textContent='Felugró ablak megnyitása';$('swp-prompt-message').textContent=`A webhely új lapot szeretne megnyitni: ${p.target||''}`}else if(p.kind==='clear-data'){$('swp-prompt-title').textContent='Webhelyadatok törlése';$('swp-prompt-message').textContent='Aktív letöltés vagy hanglejátszás fut. Biztosan folytatod?'}else{const names:any={camera:'kamerához',microphone:'mikrofonhoz',notifications:'értesítésekhez'};$('swp-prompt-title').textContent='Engedélykérés';$('swp-prompt-message').textContent=`A webhely hozzáférést kér a ${names[p.permission||'']||p.permission}.`}for(const b of Array.from(root.querySelectorAll<HTMLButtonElement>('[data-decision]'))){b.dataset.id=p.id;b.hidden=p.kind==='clear-data'&&(b.dataset.decision==='always-allow'||b.dataset.decision==='always-block');b.textContent=p.kind==='clear-data'&&b.dataset.decision==='once'?'Törlés':b.dataset.decision==='deny'?'Most nem':b.dataset.decision==='always-block'?'Mindig tiltás':b.dataset.decision==='always-allow'?'Mindig engedélyezés':'Egyszer engedélyezés'}}
function render(next:State){state=mode==='downloads'?{...next,panel:'downloads'}:mode==='panel'&&overlayClosing&&!next.panel?{...next,panel:lastPanel}:next;if(mode==='panel'&&next.panel){lastPanel=next.panel;overlayClosing=false;document.body.classList.remove('overlay-closing')}const signature=JSON.stringify(state);if(signature===lastSignature)return;lastSignature=signature;if(mode==='tool')renderTool();else if(mode==='download-confirm')renderConfirm();else if(mode==='js-dialog')renderJsDialog();else if(mode==='swp-prompt')renderSwpPrompt();else renderPanel()}
$('panel-close').onclick=()=>command(mode==='downloads'?'downloads-close':'panel',mode==='downloads'?undefined:'close');$('download-confirm-accept').onclick=e=>command('download-confirm',(e.currentTarget as HTMLButtonElement).dataset.id);$('download-confirm-custom').onclick=e=>command('download-confirm-custom',(e.currentTarget as HTMLButtonElement).dataset.id);$('download-confirm-cancel').onclick=e=>command('download-reject',(e.currentTarget as HTMLButtonElement).dataset.id);window.onkeydown=e=>{if(e.key==='Escape'&&state?.pendingDownload)command('download-reject',state.pendingDownload.id)}
$('js-dialog-card').onsubmit=e=>{e.preventDefault();answerDialog(true)};$('js-dialog-cancel').onclick=()=>answerDialog(false);window.addEventListener('keydown',e=>{if(e.key==='Escape'&&state?.jsDialog)answerDialog(false)})
$('swp-prompt').querySelectorAll<HTMLButtonElement>('[data-decision]').forEach(b=>b.onclick=()=>command('swp-prompt-answer',JSON.stringify({id:b.dataset.id,decision:b.dataset.decision})))
browser.onState(render);browser.onOverlayClose(()=>{overlayClosing=true;document.body.classList.add('overlay-closing')});void browser.command('state').then(s=>{if(s&&typeof s!=='string')render(s)});createIcons({icons:{X,Download,Globe,Shield}})
if(mode==='tool')new MutationObserver(()=>requestAnimationFrame(()=>{const root=$('tool-popover');if(!root.hidden)command('tool-height',String(root.scrollHeight))})).observe($('tool-popover'),{childList:true,subtree:true,characterData:true})
